# Generated by Django 3.2.6 on 2021-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(related_name='photo', to='gallery.Photo'),
        ),
    ]
