# Generated by Django 3.2.6 on 2022-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-create_date'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-create_date'], 'verbose_name': 'Фото для галереи', 'verbose_name_plural': 'Фото для галереи'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='captions',
            field=models.TextField(blank=True, max_length=250, verbose_name='Подпись к галерее'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(related_name='photo', to='gallery.Photo', verbose_name='Фото галереи'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование галереи'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL галереи'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='captions',
            field=models.TextField(blank=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL фото'),
        ),
    ]
