# Generated by Django 3.2.6 on 2022-04-17 14:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_about_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-id'], 'verbose_name': 'Страница "О нас"', 'verbose_name_plural': 'Страница "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ['-id'], 'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-create_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='imageabout',
            options={'ordering': ['-id'], 'verbose_name': 'Изображения для страницы "О нас"', 'verbose_name_plural': 'Изображения для страницы "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['-id'], 'verbose_name': 'Социальные ссылки', 'verbose_name_plural': 'Социальные ссылки'},
        ),
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=ckeditor.fields.RichTextField(verbose_name='Коротенький текст для предпросмотра'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст страницы "О нас"'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='icon',
            field=models.FileField(upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Информация для пользователей (номер, почта и тд.)'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email-адрес'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='alt',
            field=models.CharField(max_length=100, verbose_name='Текст, если картинка не загрузится'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imageabout',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='contact.about', verbose_name='Для страницы "О нас"'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование социальной ссылки'),
        ),
    ]
