# Generated by Django 3.2.6 on 2022-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220417_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create_at'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
    ]
